config/routes.rb
Rails.application.routes.draw do
  root to: 'properties#index'
  resources :properties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/near_station.rb
class NearStation < ApplicationRecord
  belongs_to :property

  validates :route_name, presence: true
  validates :station_name, presence: true
  validates :minutes, presence: true
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :near_stations
  accepts_nested_attributes_for :near_stations, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
  validates :rent, presence: true
  validates :address, presence: true
  validates :age, presence: true
  validates :remarks, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i(show edit update destroy)

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
    @property.near_stations.new
  end

  # GET /properties/1/edit
  def edit
       @property.near_stations.new
  end
  
  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:name, :rent, :address, :age, :remarks,
                                        near_stations_attributes: %i(route_name station_name minutes))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :物件名 %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :賃料 %>
    <%= form.number_field :rent %>
  </div>

  <div class="field">
    <%= form.label :所在地 %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :築年数 %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :備考 %>
    <%= form.text_area :remarks %>
  </div>

  <% n = 0 %>
  <%= form.fields_for :near_stations do |stations| %>
    <h2>最寄駅<%= n += 1 %></h2>
    <%= stations.label "路線名" %>
    <%= stations.text_field :route_name %>
    <%= stations.label "駅名" %>
    <%= stations.text_field :station_name %>
    <%= stations.label "徒歩分数" %>
    <%= stations.text_field :minutes %>
  <% end %>

  <div class="actions">
    <%= form.submit "物件を登録する" %>
  </div>

<% end %>

app/views/properties/edit.html.erb
<h1>物件編集</h1>

<%= render 'form', property: @property %>

<%= link_to '詳細', @property %> |
<%= link_to '戻る', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>物件一覧</h1>

<table>
  <thead>
    <tr>
      <th>物件名</th>
      <th>賃料</th>
      <th>所在地</th>
      <th>築年数</th>
      <th>備考</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.rent %><%="円"%></td>
        <td><%= property.address %></td>
        <td><%= property.age %><%="年"%></td>
        <td><%= property.remarks %></td>
        <td><%= link_to '詳細', property %></td>
        <td><%= link_to '編集', edit_property_path(property) %></td>
        <td><%= link_to '削除', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '物件を登録する', new_property_path %>

app/views/properties/new.html.erb
<h1>物件登録</h1>

<%= render 'form', property: @property %>

<%= link_to '戻る', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<h1>閲覧</h1>
  <p>
    <strong>物件名:</strong>
    <%= @property.name %>
  </p>

  <p>
    <strong>賃料:</strong>
    <%= @property.rent %><%="円"%>
  </p>

  <p>
    <strong>所在地:</strong>
    <%= @property.address %>
  </p>

  <p>
    <strong>築年数:</strong>
    <%= @property.age %><%="年"%>
  </p>

  <p>
    <strong>備考:</strong>
    <%= @property.remarks %>
  </p>

  <% n = 0 %>
    <% @property.near_stations.each do |station|%>
        <h3>最寄り駅<%= n += 1 %></h3>
          <p>路線名:<%= station.route_name %></p>
          <p>駅名：<%= station.station_name %></p>
          <p>徒歩分数：<%= station.minutes %>分</p>
    <% end %>

<%= link_to '編集', edit_property_path(@property) %> |
<%= link_to '戻る', properties_path %>